language: node_js
os:
  - osx
node_js:
  - 10.13
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache: npm
notifications:
  email:
    - markus.felten@gmx.de
before_install: []
before_script:
  - npm prune
  - npm install -g --production coveralls codecov
  - 'curl -O http://mfelten.de/Symatem/Symatem-$(uname -m)-$(uname -s)-macho.5eab774.tar'
  - tar xvf Symatem-$(uname -m)-$(uname -s)-macho.5eab774.tar SymatemMP
  - rm Symatem-$(uname -m)-$(uname -s)-macho.5eab774.tar
script:
  - npm run cover
  - npm run lint
  - npm run docs
after_script:
  - codecov
  - cat ./coverage/lcov.info | coveralls
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
